//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WANTED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interpol
    {
        public int Id { get; set; }
        public string Nombre_Pila { get; set; }
        public string Nombre { get; set; }
        public string Fecha_Nacimiento { get; set; }
        public string entity_id { get; set; }
        public string Nacionalidad { get; set; }
        public string Nacionalidad2 { get; set; }
        public string LinkImagen { get; set; }
        public string LinkServicio { get; set; }
        public string Pais_Incidente { get; set; }
        public string Idioma_Hablado { get; set; }
        public string Cargos { get; set; }
        public string Interpretacion_Cargos { get; set; }
        public string Peso_Corporal { get; set; }
        public string Altura { get; set; }
        public string Genero { get; set; }
        public string Pais_Nacimiento { get; set; }
        public string Lugar_Nacimiento { get; set; }
        public string Marcas_Distintivas { get; set; }
        public string Codigo_Color_Ojos { get; set; }
        public string Codigo_Color_Cabello { get; set; }
        public byte[] Imagen { get; set; }
    }
}
