//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WANTED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intl_Buscados
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string Detalle { get; set; }
        public string Link_Imagen { get; set; }
        public string Genero { get; set; }
        public string Nacionalidad { get; set; }
        public string Edad_Minima { get; set; }
        public string Categoria { get; set; }
        public string Lugar_Nacimiento { get; set; }
        public string Rango_Edad { get; set; }
        public string Fecha_Nacimiento { get; set; }
        public string Observaciones { get; set; }
    }
}
