//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WANTED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intl_Buscados
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public string Detalle { get; set; }
        public string Link_Imagen { get; set; }
        public string Genero { get; set; }
        public string Nacionalidad { get; set; }
        public string Edad_Minima { get; set; }
        public string Categoria { get; set; }
        public string Lugar_Nacimiento { get; set; }
        public string Rango_Edad { get; set; }
        public string Fecha_Nacimiento { get; set; }
        public string Observaciones { get; set; }
        public byte[] Imagen { get; set; }

    }
}
